### PR TITLE
Updated prefabs to follow new pattern that colliders require a rigid body

### PR DESCRIPTION
**Pull request by moraaar**
**IMPORTANT: Please approve but DO NOT merge this PR yet!** 

@moraaar will merge it once the work in [PhysX_StaticRigidBody_Staging](https://github.com/aws-lumberyard-dev/o3de/tree/PhysX_StaticRigidBody_Staging) branch is in o3de/development.

More information about this update here: https://github.com/o3de/o3de/pull/14261

Steps done:
- Open Editor.
- Run command `ed_physxUpdatePrefabsWithColliderComponents`.

Signed-off-by: moraaar <moraaar@amazon.com>

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Changes look good, would be interesting to know what the asset hint is (tagging @AMZN-stankowi and @amzn-mike for visibility who might be able to explain). Otherwise looks good :+1:

**Comment by AMZN-stankowi** [comment]
The asset hint is intended to be a human readable description of what's in the UUID field. Ideally, the UUID is the source of truth, it will eventually persist during asset relocation, for example, making it more stable.

There have been some cases where the asset hint has been used as an alternative or fallback when the UUID is not available. I forget specifics.

I have a question about these prefabs: Are they basically just 1:1 representations of the associated FBX files? If so, would it make sense to migrate these to procedural prefabs, instead? Then no one would have to run updates like this, you would just need to update the Python logic that constructs the procedural prefabs for these FBX files.

**Review by spham-amzn — APPROVED** [review]

**Comment by moraaar** [comment]
>I have a question about these prefabs: Are they basically just 1:1 representations of the associated FBX files? If so, would it make sense to migrate these to procedural prefabs, instead? Then no one would have to run updates like this, you would just need to update the Python logic that constructs the procedural prefabs for these FBX files.

That's a good question. Not sure who would know about the contents of this repo, tagging a few people that might know @adamdbrw @shawstar and @HogJonny-AMZN. 

Just to be clear, this is a separate topic and won't block this PR. It'd be better to discuss this in another way, new issue or new discussion (although I noticed this repo doesn't have the discussion tab, maybe it can be added).

**Comment by adamdbrw** [comment]
@moraaar @AMZN-stankowi aside from the FBX files, these prefabs also include generated collider meshes (typically either triangle meshes or convexes). If this could be preserved with the procedural prefabs and they are treated in the same way otherwise then I see no issues here.

**Comment by AMZN-stankowi** [comment]
There are two paths forward there:
1) If the collision mesh needs are simple and follow a pattern you would expect to work in most cases, I would talk to the game objects team about getting collider support added to the default procedural prefab system. This would be great because it would benefit a lot of people.

2) If the needs aren't that simple: With non-default procedural prefabs from FBX files, you build a python script that constructs the prefab. In this case you have full access to the O3DE scene generated from the FBX file in memory and can do whatever you want, so you could find the collision meshes and create appropriate components on a prefab.

**Comment by adamdbrw** [comment]
@AMZN-stankowi it would be good to have a default generator with a good default value (for example, by default, generate convex mesh for each) which can be changed by the user (for example, they need triangle meshes for their custom collision logic).

Python scripting is a great option and something that further enhances the degree of control.

**Pull request merged**
